import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import SessionWrapper from "@/components/SessionWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Inbox Pilot - Cold emails personalizer",
  description: "Generated by create next app",
  icons: '/favicon.ico',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <SessionWrapper>
      <body>
        <div className="text-white min-h-screen bg-[#071021]">
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
      </SessionWrapper>
    </html>
  );
}
