import { Inter, Roboto_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import SessionWrapper from "@/components/SessionWrapper";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Inbox Pilot - Cold emails personalizer",
  description: "Generated by create next app",
  icons: '/favicon.ico',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${inter.variable} ${robotoMono.variable}`}>
      <SessionWrapper>
      <body>
        <div className="text-white min-h-screen bg-[#071021] pt-18">
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
      </SessionWrapper>
    </html>
  );
}
